[package]
name = "testing_diesel"
version = "0.1.0"
authors = ["Damien Castelltort <dcastelltort@gmail.com>"]

[dependencies]
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"